keychain_ajty = 'AJTY-KEYCHAIN'

version_number = flutter_version()["version_name"]
build_number = ENV["CI_PIPELINE_ID"] + (ENV["CI_COMMIT_REF_NAME"] == 'master' ? '.0' : '.9')

default_platform(:ios)
platform :ios do
  
  desc "Push a new beta build to TestFlight"
  lane :beta do
    cocoapods
    
    increment_version_number(
      xcodeproj: "Runner.xcodeproj",
      version_number: version_number 
    )
    
    increment_build_number(
      xcodeproj: "Runner.xcodeproj",
      build_number: build_number
    )

    create_keychain(
      name: keychain_ajty,
      password: keychain_ajty,
      default_keychain: 'false',
      unlock: 'true',
      lock_when_sleeps: 'false'
    )
    
    match(
      type: "appstore",
      readonly: 'false',
      keychain_name: keychain_ajty,
      keychain_password: keychain_ajty,
    )
    
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_options: {
      method: "app-store",
        provisioningProfiles: { 
          "cz.ajty.scm" => "match AppStore cz.ajty.scm"
        }
      }
    )
    
    upload_to_testflight
  end


  desc "Promotes Testflight build for production"
  lane :production do
  
    deliver(
      build_number: build_number,
      submit_for_review: true,
      automatic_release: true,
      force: true, 
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true,
      submission_information: "{\"export_compliance_uses_encryption\": false, \"add_id_info_uses_idfa\": false }"
    )

    add_git_tag(
      tag: "#{version_name} (#{build_number}) AppStore"
    )

    push_git_tags
  end

  desc "Handles DSYMs"
  lane :monitoring do 
    download_dsyms
    upload_symbols_to_sentry
  end


end

after_all do |lane|
  delete_keychain(name: keychain_ajty)
end
