update_fastlane

default_platform(:android)

platform :android do  
  
  desc "Submits the APK to Google Play internal testing track"
  
  desc "Promote Internal to Alpha"
  lane :upload_to_play_store_alpha do
    upload_to_play_store(
      track: 'alpha',
      version_code: ENV["CI_PIPELINE_IID"],
      apk: '../build/app/outputs/apk/release/app-release.apk',
      json_key_data: ENV['JSON_KEY_DATA'],
      skip_upload_changelogs: true
    )
  end

  desc "Promote prod to production"
  lane :promote_prod_to_production do
    upload_to_play_store(
      track: 'production',
      version_code: ENV["CI_PIPELINE_IID"],
      apk: '../build/app/outputs/apk/release/app-release.apk',
      json_key_data: ENV['JSON_KEY_DATA'],
      skip_upload_changelogs: true
    )
  end
end